
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MatrimonyAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FamilyDetail
{

    public int Id { get; set; }

    public Nullable<int> FamilytypeId { get; set; }

    public Nullable<int> FamilystatusId { get; set; }

    public string FathersSurname { get; set; }

    public string FathersName { get; set; }

    public string FathersOccupation { get; set; }

    public string MothersSurname { get; set; }

    public string MothersName { get; set; }

    public string MothersOccupation { get; set; }

    public Nullable<int> NoOfSisters { get; set; }

    public Nullable<int> NoOfBrothers { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<int> ModifiedBy { get; set; }



    public virtual FamilyStatu FamilyStatu { get; set; }

    public virtual FamilyType FamilyType { get; set; }

    public virtual User User { get; set; }

}

}
