//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrimonyAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatrimonydbEntities : DbContext
    {
        public MatrimonydbEntities()
            : base("name=MatrimonydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annualincome> Annualincomes { get; set; }
        public virtual DbSet<BodyType> BodyTypes { get; set; }
        public virtual DbSet<Cast> Casts { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Complexion> Complexions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<FamilyDetail> FamilyDetails { get; set; }
        public virtual DbSet<FamilyStatu> FamilyStatus { get; set; }
        public virtual DbSet<FamilyType> FamilyTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Height> Heights { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Occupation> Occupations { get; set; }
        public virtual DbSet<Otp> Otps { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<PartnerPreferance> PartnerPreferances { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PermanantAddress> PermanantAddresses { get; set; }
        public virtual DbSet<PhysicalProfileInfo> PhysicalProfileInfoes { get; set; }
        public virtual DbSet<PhysicalStatu> PhysicalStatus { get; set; }
        public virtual DbSet<ProfileFor> ProfileFors { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Star> Stars { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserInterestedInProfile> UserInterestedInProfiles { get; set; }
        public virtual DbSet<UserPackage> UserPackages { get; set; }
        public virtual DbSet<UserPhoto> UserPhotoes { get; set; }
        public virtual DbSet<VendorForClient> VendorForClients { get; set; }
        public virtual DbSet<WorkAddress> WorkAddresses { get; set; }
    }
}
