
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MatrimonyAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProfileFor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProfileFor()
    {

        this.Users = new HashSet<User>();

    }


    public int Id { get; set; }

    public string ProfileForName { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<int> ModifiedBy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> Users { get; set; }

}

}
