
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MatrimonyAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.FamilyDetails = new HashSet<FamilyDetail>();

        this.Notifications = new HashSet<Notification>();

        this.Otps = new HashSet<Otp>();

        this.PartnerPreferances = new HashSet<PartnerPreferance>();

        this.PermanantAddresses = new HashSet<PermanantAddress>();

        this.PhysicalProfileInfoes = new HashSet<PhysicalProfileInfo>();

        this.UserInterestedInProfiles = new HashSet<UserInterestedInProfile>();

        this.UserInterestedInProfiles1 = new HashSet<UserInterestedInProfile>();

        this.UserPackages = new HashSet<UserPackage>();

        this.UserPhotoes = new HashSet<UserPhoto>();

        this.VendorForClients = new HashSet<VendorForClient>();

        this.VendorForClients1 = new HashSet<VendorForClient>();

        this.WorkAddresses = new HashSet<WorkAddress>();

    }


    public int Id { get; set; }

    public Nullable<int> RoleId { get; set; }

    public Nullable<int> ProfileForId { get; set; }

    public Nullable<int> GenderId { get; set; }

    public string FullName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> Languageid { get; set; }

    public Nullable<int> ReligionId { get; set; }

    public Nullable<int> CastId { get; set; }

    public Nullable<int> CountryId { get; set; }

    public Nullable<int> StateId { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public Nullable<int> CityId { get; set; }

    public string Village { get; set; }

    public string PostalCode { get; set; }

    public string MobileNumber { get; set; }

    public string EmailId { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public Nullable<bool> EmailConfirmed { get; set; }

    public Nullable<bool> MobileNumberConfirmed { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<int> ModifiedBy { get; set; }

    public string Termsandconditions { get; set; }

    public string GUID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FamilyDetail> FamilyDetails { get; set; }

    public virtual Gender Gender { get; set; }

    public virtual Language Language { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notification> Notifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Otp> Otps { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PartnerPreferance> PartnerPreferances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PermanantAddress> PermanantAddresses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PhysicalProfileInfo> PhysicalProfileInfoes { get; set; }

    public virtual ProfileFor ProfileFor { get; set; }

    public virtual Religion Religion { get; set; }

    public virtual Role Role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserInterestedInProfile> UserInterestedInProfiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserInterestedInProfile> UserInterestedInProfiles1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserPackage> UserPackages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserPhoto> UserPhotoes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VendorForClient> VendorForClients { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VendorForClient> VendorForClients1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<WorkAddress> WorkAddresses { get; set; }

    public virtual City City { get; set; }

    public virtual Country Country { get; set; }

    public virtual District District { get; set; }

    public virtual State State { get; set; }

}

}
