
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MatrimonyAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class WorkAddress
{

    public int Id { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public Nullable<int> CountryId { get; set; }

    public Nullable<int> StateId { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public Nullable<int> CityId { get; set; }

    public string AddressType { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<int> ModifiedBy { get; set; }



    public virtual User User { get; set; }

    public virtual City City { get; set; }

    public virtual Country Country { get; set; }

    public virtual District District { get; set; }

    public virtual State State { get; set; }

}

}
